### ISSUE TITLE
Backup and Restore Option not available on Graylog 2.1.2 version

### ISSUE THREAD

**Issue by ankush-grover-3pg** [fbalicchia/graylog-plugin-backup-configuration#2] opened 2016-12-21 03:12 UTC
Hi,

Firstly, thanks for writing this plugin. I am running Graylog 2.1.2 version on Centos 7 64-bit. I have installed the backup plugin through rpm and restarted Graylog server. I do not see the backup plugin on the Configurations Page whereas in the logs it says the Plugin is loaded. Then I removed the backup-plugin rpm and installed the plugin through the jar but still the same issue. 

Can you please tell me how to fix this issue. Do let me know if you need any further information..

2016-12-19T17:49:14.681+05:30 INFO  [CmdLineTool] Loaded plugin: BackupConfig 1.0.1 [org.graylog.plugins.BackupConfigPlugin]
2016-12-19T17:49:16.247+05:30 INFO  [BackupConfigModule] graylog-plugin-backup-configuration plagin started
2016-12-19T17:49:25.700+05:30 INFO  [Periodicals] Starting [org.graylog.plugins.backup.BackupConfigPeriodical] periodical in [0s], polling every [60s].
2016-12-19T17:49:36.588+05:30 WARN  [AuditEventModelProcessor] REST endpoint not included in audit trail:   POST /plugins/org.graylog.plugins.backup//launchrestore

Thanks & Regards

Ankush Grover

**Comment by khmermega** [comment] 2017-02-07 12:03
Having the same issue.

**Comment by fbalicchia** [comment] 2017-02-07 13:35
Hi  @ankush-grover-3pg  and @khmermega 
As you describe seems that plugin can't register service on the server strange. Probably released jar has typo annotation . I also noticed that in the readMe there is a dead link.
Did you try to use head version ?
I'll see this issue soon 

Thanks and sorry for delay

**Comment by fbalicchia** [comment] 2017-02-12 08:06
@ankush-grover-3pg  and @khmermega . I've fix the problem. The first release was cut around a Graylog beta version :-\ . please checkout the last version

**Comment by khmermega** [comment] 2017-02-13 02:55
@fbalicchia, still got the same issue
`2017-02-13T02:36:17.645Z INFO  [CmdLineTool] Loaded plugin: BackupConfiguration 1.0.2 [org.graylog.plugins.backup.BackupConfigurationPlugin]
2017-02-13T02:36:18.517Z INFO  [BackupConfigurationModule] graylog-plugin-backup-configuration plugin started
2017-02-13T02:36:25.203Z INFO  [Periodicals] Starting [org.graylog.plugins.backup.BackupConfigurationPeriodical] periodical in [0s], polling every [60s].
`
Graylog 2.1.2 and Backup v 1.0.2

**Comment by fbalicchia** [comment] 2017-02-13 06:22
I' ll check

**Comment by fbalicchia** [comment] 2017-02-13 07:56
Hi @khmermega  thanks for feedback. I' ve replace jar released by Travis with one cut from local machine.
Could you please test it ? Put it in your plugins directory, remove old, and restart your server.

**Comment by khmermega** [comment] 2017-02-13 10:20
Just tested and it show in GUI. but the backup file was empty  **graylogyyyyMMddHHmm.zip** ??
Check the below error logs 
'org.graylog.plugins.backup.BackupException: Error during backup configuration
	at org.graylog.plugins.backup.strategy.FsBackupStrategy.saveData(FsBackupStrategy.java:63) ~[graylog-plugin-backup-configuration-1.0.2.jar:?]
	at org.graylog.plugins.backup.service.impl.BackupServiceImpl.doDump(BackupServiceImpl.java:101) ~[graylog-plugin-backup-configuration-1.0.2.jar:?]
	at org.graylog.plugins.backup.service.impl.BackupServiceImpl.start(BackupServiceImpl.java:72) ~[graylog-plugin-backup-configuration-1.0.2.jar:?]
	at org.graylog.plugins.backup.BackupConfigurationPeriodical.doRun(BackupConfigurationPeriodical.java:92) [graylog-plugin-backup-configuration-1.0.2.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: org.zeroturnaround.zip.ZipException: Given directory '/opt/backup/graylog' doesn't contain any files!
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1374) ~[?:?]
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1340) ~[?:?]
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1168) ~[?:?]
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1151) ~[?:?]
	at org.graylog.plugins.backup.strategy.FsBackupStrategy.pack(FsBackupStrategy.java:152) ~[?:?]
	at org.graylog.plugins.backup.strategy.FsBackupStrategy.saveData(FsBackupStrategy.java:59) ~[?:?]
'

Thanks!

**Comment by fbalicchia** [comment] 2017-02-13 21:13
first update a configuration for example 

* threshold PT1M (every minute)
* Select Enable Backup process 
* Configure directory where you want to put your dump backup directory `/tmp/data/bck` and restore directory under `/tmp/data/restore`
* Check where is installed mongoDump in my case /usr/bin


Now every minute Graylog make a dump of your system. 

To restore data you need to put a zip file under restore folder in this case `/tmp/data/restore` then from GUI click restore data

**Comment by khmermega** [comment] 2017-02-14 04:26
From my graylog to mongodb are using username and password Auth. I can confirm that configuration of GUI is correct and every minute your plugin trying to mongodump there's an error in mongo log
`Tue Feb 14 04:22:40.384 [initandlisten] connection accepted from 127.0.0.1:53646 #63 (8 connections now open)
Tue Feb 14 04:22:40.384 [conn63] assertion 16550 not authorized for query on graylog.system.indexes ns:graylog.system.indexes query:{}
`

**Comment by fbalicchia** [comment] 2017-02-14 06:37
Did you try to execute backup as Graylog administrator ?

**Comment by khmermega** [comment] 2017-02-14 06:41
Yes sure, it has been executed by admin account. I got only an empty folder and empty backup *.zip

**Comment by fbalicchia** [comment] 2017-02-14 06:52
Ok probably you run your Mongo Instance with "--auth". At the moment plugin doesn't manage this case.
I'll support this case As soon as possibile
I'll close this issue and open new to manage this case
Thanks for help

**Closed as completed** 2017-02-14 06:53 UTC
